# Generated by Django 5.0.6 on 2024-06-18 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('subCategoryId', models.AutoField(primary_key=True, serialize=False)),
                ('subCategoryName', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='productapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='SubProduct',
            fields=[
                ('subProductId', models.AutoField(primary_key=True, serialize=False)),
                ('subProductName', models.CharField(max_length=100)),
                ('subCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subproducts', to='productapp.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='SelectedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productapp.product')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productapp.subcategory')),
                ('subproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productapp.subproduct')),
            ],
        ),
    ]
